version: '3'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d foundation_db"]
      interval: 5s
      timeout: 3s
      retries: 5

    
  auth-service:
    env_file:
      - .env
    build:
      context: . 
      dockerfile: ./backend/auth_service/Dockerfile
    volumes:
      - ./backend/auth_service:/app
      - ./backend/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy 
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 


  # foundation-service:
  #   env_file:
  #     - .env
  #   build:
  #     context: . 
  #     dockerfile: ./backend/foundation_service/Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8001:8000"


  # payment-service:
  #   env_file:
  #     - .env
  #   build:
  #     context: . 
  #     dockerfile: ./backend/payment_service/Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8002:8000"


  # analitic-service:
  #   env_file:
  #     - .env
  #   build:
  #     context: . 
  #     dockerfile: ./backend/analitic_service/Dockerfile
  #   depends_on:
  #     - postgres
  #     - auth-service
  #   ports:
  #     - "8003:8000"


volumes:
  postgres_data:



